/**
 * Edit stars, positions, and project data here.
 * `sizeScale` varies visual star size (about 0.7–1.4).
 * `selectEffect`: rings | burst | sparkle | hex | beam
 * `selectSound`: Web Audio chime (freq in Hz, optional wave)
 */
export const CONSTELLATION = {
  name: 'Orion',
  stars: [
    {
      id: 'betelgeuse',
      label: 'Nebula Auth',
      greekLabel: 'α Orionis',
      x: 0.34,
      y: 0.2,
      sizeScale: 1.25,
      selectEffect: 'rings',
      selectSound: { wave: 'sine', freq: 392, duration: 0.14 },
      order: 1,
      details: {
        description: 'OAuth2 provider with constellation-themed admin and audit trails.',
        stack: ['TypeScript', 'Node', 'PostgreSQL'],
        link: 'https://example.com',
        date: '2024',
      },
    },
    {
      id: 'bellatrix',
      label: 'Bellatrix UI',
      greekLabel: 'γ Orionis',
      x: 0.58,
      y: 0.19,
      sizeScale: 0.85,
      selectEffect: 'burst',
      selectSound: { wave: 'triangle', freq: 523.25, duration: 0.1 },
      order: 2,
      details: {
        description: 'Component library and design tokens for deep-space dashboards.',
        stack: ['React', 'Storybook', 'CSS'],
        link: 'https://example.com',
        date: '2024',
      },
    },
    {
      id: 'mintaka',
      label: 'Mintaka API',
      greekLabel: 'δ Orionis',
      x: 0.44,
      y: 0.42,
      sizeScale: 1.1,
      selectEffect: 'sparkle',
      selectSound: { wave: 'sine', freq: 659.25, duration: 0.08 },
      order: 3,
      details: {
        description: 'GraphQL federation layer with typed resolvers and tracing.',
        stack: ['GraphQL', 'Go'],
        link: 'https://example.com',
        date: '2025',
      },
    },
    {
      id: 'alnilam',
      label: 'Alnilam Pipeline',
      greekLabel: 'ε Orionis',
      x: 0.52,
      y: 0.44,
      sizeScale: 0.95,
      selectEffect: 'hex',
      selectSound: { wave: 'square', freq: 440, duration: 0.06 },
      order: 4,
      details: {
        description: 'Streaming ETL with checkpointed stages and observability.',
        stack: ['Python', 'DuckDB'],
        link: 'https://example.com',
        date: '2025',
      },
    },
    {
      id: 'alnitak',
      label: 'Alnitak Edge',
      greekLabel: 'ζ Orionis',
      x: 0.6,
      y: 0.47,
      sizeScale: 1.15,
      selectEffect: 'beam',
      selectSound: { wave: 'sawtooth', freq: 349.23, duration: 0.11 },
      order: 5,
      details: {
        description: 'Regional edge workers for low-latency chart updates.',
        stack: ['Rust', 'Workers'],
        link: 'https://example.com',
        date: '2024',
      },
    },
    {
      id: 'rigel',
      label: 'Rigel Analytics',
      greekLabel: 'β Orionis',
      x: 0.63,
      y: 0.66,
      sizeScale: 1.35,
      selectEffect: 'rings',
      selectSound: { wave: 'sine', freq: 783.99, duration: 0.16 },
      order: 6,
      details: {
        description: 'Real-time analytics with adaptive sampling under load.',
        stack: ['ClickHouse', 'React'],
        link: 'https://example.com',
        date: '2023',
      },
    },
    {
      id: 'saiph',
      label: 'Saiph Mobile',
      greekLabel: 'κ Orionis',
      x: 0.36,
      y: 0.7,
      sizeScale: 0.78,
      selectEffect: 'burst',
      selectSound: { wave: 'triangle', freq: 293.66, duration: 0.12 },
      order: 7,
      details: {
        description: 'Companion app for field observations and offline maps.',
        stack: ['Swift', 'Kotlin'],
        link: 'https://example.com',
        date: '2023',
      },
    },
  ],
  connections: [
    ['betelgeuse', 'bellatrix'],
    ['bellatrix', 'mintaka'],
    ['mintaka', 'alnilam'],
    ['alnilam', 'alnitak'],
    ['alnitak', 'rigel'],
    ['alnitak', 'saiph'],
  ],
}
