export const MAP_META = {
  title: 'SECTOR 7 — PORTFOLIO',
  totalNodes: 8,
};

export const SECTORS = [
  { id: 'design', label: 'DESIGN', x0: 0, x1: 0.33 },
  { id: 'dev', label: 'DEV', x0: 0.33, x1: 0.66 },
  { id: 'lab', label: 'EXPERIMENTS', x0: 0.66, x1: 1 },
];

export const NODES = [
  {
    id: 'node-0-1',
    label: '0-1',
    title: 'Nebula Dashboard',
    subtitle: 'Web App · 2024',
    description:
      'A tactical analytics dashboard with real-time charts and a star-map aesthetic. Built for clarity under pressure.',
    stack: ['React', 'Node.js', 'WebSocket'],
    link: 'https://example.com',
    status: 'complete',
    type: 'pulsar',
    previewColor: '#4e9fff',
    category: 'web',
    x: 0.08,
    y: 0.42,
    depth: 1.15,
  },
  {
    id: 'node-0-2',
    label: '0-2',
    title: 'Binary Commerce',
    subtitle: 'E‑commerce · 2023',
    description:
      'Headless storefront with edge caching and a playful checkout flow. Focus on conversion and performance.',
    stack: ['Next.js', 'Stripe', 'PostgreSQL'],
    link: 'https://example.com',
    status: 'complete',
    type: 'binary',
    previewColor: '#7dffb8',
    category: 'web',
    x: 0.22,
    y: 0.55,
    depth: 0.85,
  },
  {
    id: 'node-0-3',
    label: '0-3',
    title: 'Void CMS',
    subtitle: 'Content · 2025',
    description:
      'Markdown-first CMS with collaborative editing and versioned releases. Designed for small product teams.',
    stack: ['TypeScript', 'SQLite', 'Hono'],
    link: 'https://example.com',
    status: 'wip',
    type: 'nebula',
    previewColor: '#5b8cff',
    category: 'web',
    x: 0.38,
    y: 0.38,
    depth: 1.0,
  },
  {
    id: 'node-0-4',
    label: '0-4',
    title: 'Singularity API',
    subtitle: 'Backend · 2024',
    description:
      'High-throughput ingestion pipeline with backpressure and observability baked in. Still under heavy iteration.',
    stack: ['Go', 'Kafka', 'Prometheus'],
    link: 'https://example.com',
    status: 'wip',
    type: 'blackhole',
    previewColor: '#8899cc',
    category: 'backend',
    x: 0.52,
    y: 0.62,
    depth: 1.25,
  },
  {
    id: 'node-0-5',
    label: '0-5',
    title: 'Relay Station',
    subtitle: 'DevOps · 2023',
    description:
      'CI/CD templates and deploy hooks for static sites and edge functions. Opinionated but flexible.',
    stack: ['GitHub Actions', 'Terraform'],
    link: 'https://example.com',
    status: 'complete',
    type: 'station',
    previewColor: '#ff9f4e',
    category: 'backend',
    x: 0.65,
    y: 0.48,
    depth: 0.7,
  },
  {
    id: 'node-0-6',
    label: '0-6',
    title: 'Aurora Sketches',
    subtitle: 'Creative · 2024',
    description:
      'Generative art explorations in WebGL and Canvas. A playground for shaders and motion studies.',
    stack: ['Three.js', 'GLSL'],
    link: 'https://example.com',
    status: 'complete',
    type: 'nebula',
    previewColor: '#c86bff',
    category: 'creative',
    x: 0.78,
    y: 0.35,
    depth: 0.95,
  },
  {
    id: 'node-0-7',
    label: '0-7',
    title: 'Deep Archive',
    subtitle: 'Experiment · TBD',
    description:
      'Planned research project: semantic search over personal notes. Locked until the core indexer stabilizes.',
    stack: ['Rust', 'Embeddings'],
    link: '',
    status: 'locked',
    type: 'blackhole',
    previewColor: '#2a3560',
    category: 'lab',
    x: 0.88,
    y: 0.58,
    depth: 0.55,
  },
  {
    id: 'node-0-8',
    label: '0-8',
    title: 'Signal Forge',
    subtitle: 'Tooling · 2025',
    description:
      'CLI toolkit for scaffolding design-system tokens and exporting to multiple platforms.',
    stack: ['Node.js', 'Zod'],
    link: 'https://example.com',
    status: 'locked',
    type: 'pulsar',
    previewColor: '#3d4a7a',
    category: 'lab',
    x: 0.95,
    y: 0.72,
    depth: 1.1,
  },
];

export const ROUTES = [
  ['node-0-1', 'node-0-2'],
  ['node-0-2', 'node-0-3'],
  ['node-0-3', 'node-0-4'],
  ['node-0-4', 'node-0-5'],
  ['node-0-5', 'node-0-6'],
  ['node-0-6', 'node-0-7'],
  ['node-0-7', 'node-0-8'],
];
